// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary_exposure_key_export.proto

package protobuf;

/**
 * Protobuf type {@code protobuf.SignatureInfo}
 */
public  final class SignatureInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.SignatureInfo)
    SignatureInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SignatureInfo.newBuilder() to construct.
  private SignatureInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignatureInfo() {
    verificationKeyVersion_ = "";
    verificationKeyId_ = "";
    signatureAlgorithm_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SignatureInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            verificationKeyVersion_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            verificationKeyId_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            signatureAlgorithm_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_SignatureInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_SignatureInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.SignatureInfo.class, protobuf.SignatureInfo.Builder.class);
  }

  private int bitField0_;
  public static final int VERIFICATION_KEY_VERSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object verificationKeyVersion_;
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   */
  public boolean hasVerificationKeyVersion() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   */
  public java.lang.String getVerificationKeyVersion() {
    java.lang.Object ref = verificationKeyVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        verificationKeyVersion_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVerificationKeyVersionBytes() {
    java.lang.Object ref = verificationKeyVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verificationKeyVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFICATION_KEY_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object verificationKeyId_;
  /**
   * <pre>
   * Alias with which to identify public key to be used for verification
   * Must be in character class [a-zA-Z0-9_.]
   * For cross-compatibility with Apple, you can use your region's three-digit
   * mobile country code (MCC). If your region has more than one MCC, choose the
   * one that Apple has configured.
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   */
  public boolean hasVerificationKeyId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Alias with which to identify public key to be used for verification
   * Must be in character class [a-zA-Z0-9_.]
   * For cross-compatibility with Apple, you can use your region's three-digit
   * mobile country code (MCC). If your region has more than one MCC, choose the
   * one that Apple has configured.
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   */
  public java.lang.String getVerificationKeyId() {
    java.lang.Object ref = verificationKeyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        verificationKeyId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Alias with which to identify public key to be used for verification
   * Must be in character class [a-zA-Z0-9_.]
   * For cross-compatibility with Apple, you can use your region's three-digit
   * mobile country code (MCC). If your region has more than one MCC, choose the
   * one that Apple has configured.
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getVerificationKeyIdBytes() {
    java.lang.Object ref = verificationKeyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verificationKeyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNATURE_ALGORITHM_FIELD_NUMBER = 5;
  private volatile java.lang.Object signatureAlgorithm_;
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   */
  public boolean hasSignatureAlgorithm() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   */
  public java.lang.String getSignatureAlgorithm() {
    java.lang.Object ref = signatureAlgorithm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        signatureAlgorithm_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSignatureAlgorithmBytes() {
    java.lang.Object ref = signatureAlgorithm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signatureAlgorithm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, verificationKeyVersion_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, verificationKeyId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, signatureAlgorithm_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, verificationKeyVersion_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, verificationKeyId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, signatureAlgorithm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.SignatureInfo)) {
      return super.equals(obj);
    }
    protobuf.SignatureInfo other = (protobuf.SignatureInfo) obj;

    boolean result = true;
    result = result && (hasVerificationKeyVersion() == other.hasVerificationKeyVersion());
    if (hasVerificationKeyVersion()) {
      result = result && getVerificationKeyVersion()
          .equals(other.getVerificationKeyVersion());
    }
    result = result && (hasVerificationKeyId() == other.hasVerificationKeyId());
    if (hasVerificationKeyId()) {
      result = result && getVerificationKeyId()
          .equals(other.getVerificationKeyId());
    }
    result = result && (hasSignatureAlgorithm() == other.hasSignatureAlgorithm());
    if (hasSignatureAlgorithm()) {
      result = result && getSignatureAlgorithm()
          .equals(other.getSignatureAlgorithm());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVerificationKeyVersion()) {
      hash = (37 * hash) + VERIFICATION_KEY_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVerificationKeyVersion().hashCode();
    }
    if (hasVerificationKeyId()) {
      hash = (37 * hash) + VERIFICATION_KEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getVerificationKeyId().hashCode();
    }
    if (hasSignatureAlgorithm()) {
      hash = (37 * hash) + SIGNATURE_ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureAlgorithm().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.SignatureInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.SignatureInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.SignatureInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.SignatureInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.SignatureInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.SignatureInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.SignatureInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.SignatureInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.SignatureInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.SignatureInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.SignatureInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.SignatureInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.SignatureInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.SignatureInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.SignatureInfo)
      protobuf.SignatureInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_SignatureInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_SignatureInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.SignatureInfo.class, protobuf.SignatureInfo.Builder.class);
    }

    // Construct using protobuf.SignatureInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      verificationKeyVersion_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      verificationKeyId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      signatureAlgorithm_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_SignatureInfo_descriptor;
    }

    @java.lang.Override
    public protobuf.SignatureInfo getDefaultInstanceForType() {
      return protobuf.SignatureInfo.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.SignatureInfo build() {
      protobuf.SignatureInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.SignatureInfo buildPartial() {
      protobuf.SignatureInfo result = new protobuf.SignatureInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.verificationKeyVersion_ = verificationKeyVersion_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.verificationKeyId_ = verificationKeyId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.signatureAlgorithm_ = signatureAlgorithm_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.SignatureInfo) {
        return mergeFrom((protobuf.SignatureInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.SignatureInfo other) {
      if (other == protobuf.SignatureInfo.getDefaultInstance()) return this;
      if (other.hasVerificationKeyVersion()) {
        bitField0_ |= 0x00000001;
        verificationKeyVersion_ = other.verificationKeyVersion_;
        onChanged();
      }
      if (other.hasVerificationKeyId()) {
        bitField0_ |= 0x00000002;
        verificationKeyId_ = other.verificationKeyId_;
        onChanged();
      }
      if (other.hasSignatureAlgorithm()) {
        bitField0_ |= 0x00000004;
        signatureAlgorithm_ = other.signatureAlgorithm_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.SignatureInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.SignatureInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object verificationKeyVersion_ = "";
    /**
     * <pre>
     * Key version for rollovers
     * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
     * </pre>
     *
     * <code>optional string verification_key_version = 3;</code>
     */
    public boolean hasVerificationKeyVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Key version for rollovers
     * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
     * </pre>
     *
     * <code>optional string verification_key_version = 3;</code>
     */
    public java.lang.String getVerificationKeyVersion() {
      java.lang.Object ref = verificationKeyVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          verificationKeyVersion_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Key version for rollovers
     * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
     * </pre>
     *
     * <code>optional string verification_key_version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVerificationKeyVersionBytes() {
      java.lang.Object ref = verificationKeyVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verificationKeyVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Key version for rollovers
     * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
     * </pre>
     *
     * <code>optional string verification_key_version = 3;</code>
     */
    public Builder setVerificationKeyVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      verificationKeyVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Key version for rollovers
     * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
     * </pre>
     *
     * <code>optional string verification_key_version = 3;</code>
     */
    public Builder clearVerificationKeyVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      verificationKeyVersion_ = getDefaultInstance().getVerificationKeyVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Key version for rollovers
     * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
     * </pre>
     *
     * <code>optional string verification_key_version = 3;</code>
     */
    public Builder setVerificationKeyVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      verificationKeyVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verificationKeyId_ = "";
    /**
     * <pre>
     * Alias with which to identify public key to be used for verification
     * Must be in character class [a-zA-Z0-9_.]
     * For cross-compatibility with Apple, you can use your region's three-digit
     * mobile country code (MCC). If your region has more than one MCC, choose the
     * one that Apple has configured.
     * </pre>
     *
     * <code>optional string verification_key_id = 4;</code>
     */
    public boolean hasVerificationKeyId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Alias with which to identify public key to be used for verification
     * Must be in character class [a-zA-Z0-9_.]
     * For cross-compatibility with Apple, you can use your region's three-digit
     * mobile country code (MCC). If your region has more than one MCC, choose the
     * one that Apple has configured.
     * </pre>
     *
     * <code>optional string verification_key_id = 4;</code>
     */
    public java.lang.String getVerificationKeyId() {
      java.lang.Object ref = verificationKeyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          verificationKeyId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Alias with which to identify public key to be used for verification
     * Must be in character class [a-zA-Z0-9_.]
     * For cross-compatibility with Apple, you can use your region's three-digit
     * mobile country code (MCC). If your region has more than one MCC, choose the
     * one that Apple has configured.
     * </pre>
     *
     * <code>optional string verification_key_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVerificationKeyIdBytes() {
      java.lang.Object ref = verificationKeyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verificationKeyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Alias with which to identify public key to be used for verification
     * Must be in character class [a-zA-Z0-9_.]
     * For cross-compatibility with Apple, you can use your region's three-digit
     * mobile country code (MCC). If your region has more than one MCC, choose the
     * one that Apple has configured.
     * </pre>
     *
     * <code>optional string verification_key_id = 4;</code>
     */
    public Builder setVerificationKeyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      verificationKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Alias with which to identify public key to be used for verification
     * Must be in character class [a-zA-Z0-9_.]
     * For cross-compatibility with Apple, you can use your region's three-digit
     * mobile country code (MCC). If your region has more than one MCC, choose the
     * one that Apple has configured.
     * </pre>
     *
     * <code>optional string verification_key_id = 4;</code>
     */
    public Builder clearVerificationKeyId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      verificationKeyId_ = getDefaultInstance().getVerificationKeyId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Alias with which to identify public key to be used for verification
     * Must be in character class [a-zA-Z0-9_.]
     * For cross-compatibility with Apple, you can use your region's three-digit
     * mobile country code (MCC). If your region has more than one MCC, choose the
     * one that Apple has configured.
     * </pre>
     *
     * <code>optional string verification_key_id = 4;</code>
     */
    public Builder setVerificationKeyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      verificationKeyId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object signatureAlgorithm_ = "";
    /**
     * <pre>
     * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
     * </pre>
     *
     * <code>optional string signature_algorithm = 5;</code>
     */
    public boolean hasSignatureAlgorithm() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
     * </pre>
     *
     * <code>optional string signature_algorithm = 5;</code>
     */
    public java.lang.String getSignatureAlgorithm() {
      java.lang.Object ref = signatureAlgorithm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signatureAlgorithm_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
     * </pre>
     *
     * <code>optional string signature_algorithm = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureAlgorithmBytes() {
      java.lang.Object ref = signatureAlgorithm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signatureAlgorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
     * </pre>
     *
     * <code>optional string signature_algorithm = 5;</code>
     */
    public Builder setSignatureAlgorithm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      signatureAlgorithm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
     * </pre>
     *
     * <code>optional string signature_algorithm = 5;</code>
     */
    public Builder clearSignatureAlgorithm() {
      bitField0_ = (bitField0_ & ~0x00000004);
      signatureAlgorithm_ = getDefaultInstance().getSignatureAlgorithm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
     * </pre>
     *
     * <code>optional string signature_algorithm = 5;</code>
     */
    public Builder setSignatureAlgorithmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      signatureAlgorithm_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.SignatureInfo)
  }

  // @@protoc_insertion_point(class_scope:protobuf.SignatureInfo)
  private static final protobuf.SignatureInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.SignatureInfo();
  }

  public static protobuf.SignatureInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SignatureInfo>
      PARSER = new com.google.protobuf.AbstractParser<SignatureInfo>() {
    @java.lang.Override
    public SignatureInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SignatureInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SignatureInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignatureInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.SignatureInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

