// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary_exposure_key_export.proto

package protobuf;

public interface SignatureInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.SignatureInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   */
  boolean hasVerificationKeyVersion();
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   */
  java.lang.String getVerificationKeyVersion();
  /**
   * <pre>
   * Key version for rollovers
   * Must be in character class [a-zA-Z0-9_]. For example, 'v1'
   * </pre>
   *
   * <code>optional string verification_key_version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVerificationKeyVersionBytes();

  /**
   * <pre>
   * Alias with which to identify public key to be used for verification
   * Must be in character class [a-zA-Z0-9_.]
   * For cross-compatibility with Apple, you can use your region's three-digit
   * mobile country code (MCC). If your region has more than one MCC, choose the
   * one that Apple has configured.
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   */
  boolean hasVerificationKeyId();
  /**
   * <pre>
   * Alias with which to identify public key to be used for verification
   * Must be in character class [a-zA-Z0-9_.]
   * For cross-compatibility with Apple, you can use your region's three-digit
   * mobile country code (MCC). If your region has more than one MCC, choose the
   * one that Apple has configured.
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   */
  java.lang.String getVerificationKeyId();
  /**
   * <pre>
   * Alias with which to identify public key to be used for verification
   * Must be in character class [a-zA-Z0-9_.]
   * For cross-compatibility with Apple, you can use your region's three-digit
   * mobile country code (MCC). If your region has more than one MCC, choose the
   * one that Apple has configured.
   * </pre>
   *
   * <code>optional string verification_key_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getVerificationKeyIdBytes();

  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   */
  boolean hasSignatureAlgorithm();
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   */
  java.lang.String getSignatureAlgorithm();
  /**
   * <pre>
   * ASN.1 OID for Algorithm Identifier. For example, `1.2.840.10045.4.3.2'
   * </pre>
   *
   * <code>optional string signature_algorithm = 5;</code>
   */
  com.google.protobuf.ByteString
      getSignatureAlgorithmBytes();
}
