// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary_exposure_key_export.proto

package protobuf;

public interface TemporaryExposureKeyExportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.TemporaryExposureKeyExport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Time window of keys in this batch based on arrival to server, in UTC seconds.
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   */
  boolean hasStartTimestamp();
  /**
   * <pre>
   * Time window of keys in this batch based on arrival to server, in UTC seconds.
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   */
  long getStartTimestamp();

  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   */
  boolean hasEndTimestamp();
  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   */
  long getEndTimestamp();

  /**
   * <pre>
   * Region for which these keys came from, such as country.
   * </pre>
   *
   * <code>optional string region = 3;</code>
   */
  boolean hasRegion();
  /**
   * <pre>
   * Region for which these keys came from, such as country.
   * </pre>
   *
   * <code>optional string region = 3;</code>
   */
  java.lang.String getRegion();
  /**
   * <pre>
   * Region for which these keys came from, such as country.
   * </pre>
   *
   * <code>optional string region = 3;</code>
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   */
  boolean hasBatchNum();
  /**
   * <pre>
   * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   */
  int getBatchNum();

  /**
   * <code>optional int32 batch_size = 5;</code>
   */
  boolean hasBatchSize();
  /**
   * <code>optional int32 batch_size = 5;</code>
   */
  int getBatchSize();

  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  java.util.List<protobuf.SignatureInfo> 
      getSignatureInfosList();
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  protobuf.SignatureInfo getSignatureInfos(int index);
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  int getSignatureInfosCount();
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  java.util.List<? extends protobuf.SignatureInfoOrBuilder> 
      getSignatureInfosOrBuilderList();
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  protobuf.SignatureInfoOrBuilder getSignatureInfosOrBuilder(
      int index);

  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  java.util.List<protobuf.TemporaryExposureKey> 
      getKeysList();
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  protobuf.TemporaryExposureKey getKeys(int index);
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  int getKeysCount();
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  java.util.List<? extends protobuf.TemporaryExposureKeyOrBuilder> 
      getKeysOrBuilderList();
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  protobuf.TemporaryExposureKeyOrBuilder getKeysOrBuilder(
      int index);

  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  java.util.List<protobuf.TemporaryExposureKey> 
      getRevisedKeysList();
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  protobuf.TemporaryExposureKey getRevisedKeys(int index);
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  int getRevisedKeysCount();
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  java.util.List<? extends protobuf.TemporaryExposureKeyOrBuilder> 
      getRevisedKeysOrBuilderList();
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  protobuf.TemporaryExposureKeyOrBuilder getRevisedKeysOrBuilder(
      int index);
}
