// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary_exposure_key_export.proto

package protobuf;

public final class TemporaryExposureKeyExportOuterClass {
  private TemporaryExposureKeyExportOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_TemporaryExposureKeyExport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_TemporaryExposureKeyExport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_SignatureInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_SignatureInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_TemporaryExposureKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_TemporaryExposureKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#temporary_exposure_key_export.proto\022\010p" +
      "rotobuf\"\231\002\n\032TemporaryExposureKeyExport\022\027" +
      "\n\017start_timestamp\030\001 \001(\006\022\025\n\rend_timestamp" +
      "\030\002 \001(\006\022\016\n\006region\030\003 \001(\t\022\021\n\tbatch_num\030\004 \001(" +
      "\005\022\022\n\nbatch_size\030\005 \001(\005\0220\n\017signature_infos" +
      "\030\006 \003(\0132\027.protobuf.SignatureInfo\022,\n\004keys\030" +
      "\007 \003(\0132\036.protobuf.TemporaryExposureKey\0224\n" +
      "\014revised_keys\030\010 \003(\0132\036.protobuf.Temporary" +
      "ExposureKey\"\227\001\n\rSignatureInfo\022 \n\030verific" +
      "ation_key_version\030\003 \001(\t\022\033\n\023verification_" +
      "key_id\030\004 \001(\t\022\033\n\023signature_algorithm\030\005 \001(" +
      "\tJ\004\010\001\020\002J\004\010\002\020\003R\rapp_bundle_idR\017android_pa" +
      "ckage\"\365\002\n\024TemporaryExposureKey\022\020\n\010key_da" +
      "ta\030\001 \001(\014\022#\n\027transmission_risk_level\030\002 \001(" +
      "\005B\002\030\001\022%\n\035rolling_start_interval_number\030\003" +
      " \001(\005\022\033\n\016rolling_period\030\004 \001(\005:\003144\022>\n\013rep" +
      "ort_type\030\005 \001(\0162).protobuf.TemporaryExpos" +
      "ureKey.ReportType\022$\n\034days_since_onset_of" +
      "_symptoms\030\006 \001(\021\"|\n\nReportType\022\013\n\007UNKNOWN" +
      "\020\000\022\022\n\016CONFIRMED_TEST\020\001\022 \n\034CONFIRMED_CLIN" +
      "ICAL_DIAGNOSIS\020\002\022\017\n\013SELF_REPORT\020\003\022\r\n\tREC" +
      "URSIVE\020\004\022\013\n\007REVOKED\020\005B\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_TemporaryExposureKeyExport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_TemporaryExposureKeyExport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_TemporaryExposureKeyExport_descriptor,
        new java.lang.String[] { "StartTimestamp", "EndTimestamp", "Region", "BatchNum", "BatchSize", "SignatureInfos", "Keys", "RevisedKeys", });
    internal_static_protobuf_SignatureInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_SignatureInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_SignatureInfo_descriptor,
        new java.lang.String[] { "VerificationKeyVersion", "VerificationKeyId", "SignatureAlgorithm", });
    internal_static_protobuf_TemporaryExposureKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protobuf_TemporaryExposureKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_TemporaryExposureKey_descriptor,
        new java.lang.String[] { "KeyData", "TransmissionRiskLevel", "RollingStartIntervalNumber", "RollingPeriod", "ReportType", "DaysSinceOnsetOfSymptoms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
