// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary_exposure_key_export.proto

package protobuf;

public interface TemporaryExposureKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.TemporaryExposureKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Key of infected user
   * </pre>
   *
   * <code>optional bytes key_data = 1;</code>
   */
  boolean hasKeyData();
  /**
   * <pre>
   * Key of infected user
   * </pre>
   *
   * <code>optional bytes key_data = 1;</code>
   */
  com.google.protobuf.ByteString getKeyData();

  /**
   * <pre>
   * Varying risk associated with a key depending on diagnosis method
   * </pre>
   *
   * <code>optional int32 transmission_risk_level = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasTransmissionRiskLevel();
  /**
   * <pre>
   * Varying risk associated with a key depending on diagnosis method
   * </pre>
   *
   * <code>optional int32 transmission_risk_level = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getTransmissionRiskLevel();

  /**
   * <pre>
   * The interval number since epoch for which a key starts
   * </pre>
   *
   * <code>optional int32 rolling_start_interval_number = 3;</code>
   */
  boolean hasRollingStartIntervalNumber();
  /**
   * <pre>
   * The interval number since epoch for which a key starts
   * </pre>
   *
   * <code>optional int32 rolling_start_interval_number = 3;</code>
   */
  int getRollingStartIntervalNumber();

  /**
   * <pre>
   * Increments of 10 minutes describing how long a key is valid
   * </pre>
   *
   * <code>optional int32 rolling_period = 4 [default = 144];</code>
   */
  boolean hasRollingPeriod();
  /**
   * <pre>
   * Increments of 10 minutes describing how long a key is valid
   * </pre>
   *
   * <code>optional int32 rolling_period = 4 [default = 144];</code>
   */
  int getRollingPeriod();

  /**
   * <pre>
   * Type of diagnosis associated with a key.
   * </pre>
   *
   * <code>optional .protobuf.TemporaryExposureKey.ReportType report_type = 5;</code>
   */
  boolean hasReportType();
  /**
   * <pre>
   * Type of diagnosis associated with a key.
   * </pre>
   *
   * <code>optional .protobuf.TemporaryExposureKey.ReportType report_type = 5;</code>
   */
  protobuf.TemporaryExposureKey.ReportType getReportType();

  /**
   * <pre>
   * Number of days elapsed between symptom onset and the TEK being used.
   * E.g. 2 means TEK is 2 days after onset of symptoms.
   * </pre>
   *
   * <code>optional sint32 days_since_onset_of_symptoms = 6;</code>
   */
  boolean hasDaysSinceOnsetOfSymptoms();
  /**
   * <pre>
   * Number of days elapsed between symptom onset and the TEK being used.
   * E.g. 2 means TEK is 2 days after onset of symptoms.
   * </pre>
   *
   * <code>optional sint32 days_since_onset_of_symptoms = 6;</code>
   */
  int getDaysSinceOnsetOfSymptoms();
}
