// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary_exposure_key_export.proto

package protobuf;

/**
 * Protobuf type {@code protobuf.TemporaryExposureKeyExport}
 */
public  final class TemporaryExposureKeyExport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.TemporaryExposureKeyExport)
    TemporaryExposureKeyExportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemporaryExposureKeyExport.newBuilder() to construct.
  private TemporaryExposureKeyExport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemporaryExposureKeyExport() {
    startTimestamp_ = 0L;
    endTimestamp_ = 0L;
    region_ = "";
    batchNum_ = 0;
    batchSize_ = 0;
    signatureInfos_ = java.util.Collections.emptyList();
    keys_ = java.util.Collections.emptyList();
    revisedKeys_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemporaryExposureKeyExport(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            bitField0_ |= 0x00000001;
            startTimestamp_ = input.readFixed64();
            break;
          }
          case 17: {
            bitField0_ |= 0x00000002;
            endTimestamp_ = input.readFixed64();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            region_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            batchNum_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            batchSize_ = input.readInt32();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              signatureInfos_ = new java.util.ArrayList<protobuf.SignatureInfo>();
              mutable_bitField0_ |= 0x00000020;
            }
            signatureInfos_.add(
                input.readMessage(protobuf.SignatureInfo.PARSER, extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              keys_ = new java.util.ArrayList<protobuf.TemporaryExposureKey>();
              mutable_bitField0_ |= 0x00000040;
            }
            keys_.add(
                input.readMessage(protobuf.TemporaryExposureKey.PARSER, extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              revisedKeys_ = new java.util.ArrayList<protobuf.TemporaryExposureKey>();
              mutable_bitField0_ |= 0x00000080;
            }
            revisedKeys_.add(
                input.readMessage(protobuf.TemporaryExposureKey.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        signatureInfos_ = java.util.Collections.unmodifiableList(signatureInfos_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        keys_ = java.util.Collections.unmodifiableList(keys_);
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        revisedKeys_ = java.util.Collections.unmodifiableList(revisedKeys_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_TemporaryExposureKeyExport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_TemporaryExposureKeyExport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.TemporaryExposureKeyExport.class, protobuf.TemporaryExposureKeyExport.Builder.class);
  }

  private int bitField0_;
  public static final int START_TIMESTAMP_FIELD_NUMBER = 1;
  private long startTimestamp_;
  /**
   * <pre>
   * Time window of keys in this batch based on arrival to server, in UTC seconds.
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   */
  public boolean hasStartTimestamp() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Time window of keys in this batch based on arrival to server, in UTC seconds.
   * </pre>
   *
   * <code>optional fixed64 start_timestamp = 1;</code>
   */
  public long getStartTimestamp() {
    return startTimestamp_;
  }

  public static final int END_TIMESTAMP_FIELD_NUMBER = 2;
  private long endTimestamp_;
  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   */
  public boolean hasEndTimestamp() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional fixed64 end_timestamp = 2;</code>
   */
  public long getEndTimestamp() {
    return endTimestamp_;
  }

  public static final int REGION_FIELD_NUMBER = 3;
  private volatile java.lang.Object region_;
  /**
   * <pre>
   * Region for which these keys came from, such as country.
   * </pre>
   *
   * <code>optional string region = 3;</code>
   */
  public boolean hasRegion() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Region for which these keys came from, such as country.
   * </pre>
   *
   * <code>optional string region = 3;</code>
   */
  public java.lang.String getRegion() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        region_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Region for which these keys came from, such as country.
   * </pre>
   *
   * <code>optional string region = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRegionBytes() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      region_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATCH_NUM_FIELD_NUMBER = 4;
  private int batchNum_;
  /**
   * <pre>
   * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   */
  public boolean hasBatchNum() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
   * Note: Not yet supported on iOS.
   * </pre>
   *
   * <code>optional int32 batch_num = 4;</code>
   */
  public int getBatchNum() {
    return batchNum_;
  }

  public static final int BATCH_SIZE_FIELD_NUMBER = 5;
  private int batchSize_;
  /**
   * <code>optional int32 batch_size = 5;</code>
   */
  public boolean hasBatchSize() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int32 batch_size = 5;</code>
   */
  public int getBatchSize() {
    return batchSize_;
  }

  public static final int SIGNATURE_INFOS_FIELD_NUMBER = 6;
  private java.util.List<protobuf.SignatureInfo> signatureInfos_;
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  public java.util.List<protobuf.SignatureInfo> getSignatureInfosList() {
    return signatureInfos_;
  }
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  public java.util.List<? extends protobuf.SignatureInfoOrBuilder> 
      getSignatureInfosOrBuilderList() {
    return signatureInfos_;
  }
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  public int getSignatureInfosCount() {
    return signatureInfos_.size();
  }
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  public protobuf.SignatureInfo getSignatureInfos(int index) {
    return signatureInfos_.get(index);
  }
  /**
   * <pre>
   * Information about associated signatures
   * </pre>
   *
   * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
   */
  public protobuf.SignatureInfoOrBuilder getSignatureInfosOrBuilder(
      int index) {
    return signatureInfos_.get(index);
  }

  public static final int KEYS_FIELD_NUMBER = 7;
  private java.util.List<protobuf.TemporaryExposureKey> keys_;
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  public java.util.List<protobuf.TemporaryExposureKey> getKeysList() {
    return keys_;
  }
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  public java.util.List<? extends protobuf.TemporaryExposureKeyOrBuilder> 
      getKeysOrBuilderList() {
    return keys_;
  }
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  public int getKeysCount() {
    return keys_.size();
  }
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  public protobuf.TemporaryExposureKey getKeys(int index) {
    return keys_.get(index);
  }
  /**
   * <pre>
   * The TemporaryExposureKeys for initial release of keys.
   * Keys should be included in this list for initial release,
   * whereas revised or revoked keys should go in revised_keys.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
   */
  public protobuf.TemporaryExposureKeyOrBuilder getKeysOrBuilder(
      int index) {
    return keys_.get(index);
  }

  public static final int REVISED_KEYS_FIELD_NUMBER = 8;
  private java.util.List<protobuf.TemporaryExposureKey> revisedKeys_;
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  public java.util.List<protobuf.TemporaryExposureKey> getRevisedKeysList() {
    return revisedKeys_;
  }
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  public java.util.List<? extends protobuf.TemporaryExposureKeyOrBuilder> 
      getRevisedKeysOrBuilderList() {
    return revisedKeys_;
  }
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  public int getRevisedKeysCount() {
    return revisedKeys_.size();
  }
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  public protobuf.TemporaryExposureKey getRevisedKeys(int index) {
    return revisedKeys_.get(index);
  }
  /**
   * <pre>
   * TemporaryExposureKeys that have changed status.
   * Keys should be included in this list if they have changed status
   * or have been revoked.
   * </pre>
   *
   * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
   */
  public protobuf.TemporaryExposureKeyOrBuilder getRevisedKeysOrBuilder(
      int index) {
    return revisedKeys_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeFixed64(1, startTimestamp_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeFixed64(2, endTimestamp_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, region_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, batchNum_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, batchSize_);
    }
    for (int i = 0; i < signatureInfos_.size(); i++) {
      output.writeMessage(6, signatureInfos_.get(i));
    }
    for (int i = 0; i < keys_.size(); i++) {
      output.writeMessage(7, keys_.get(i));
    }
    for (int i = 0; i < revisedKeys_.size(); i++) {
      output.writeMessage(8, revisedKeys_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, startTimestamp_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(2, endTimestamp_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, region_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, batchNum_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, batchSize_);
    }
    for (int i = 0; i < signatureInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, signatureInfos_.get(i));
    }
    for (int i = 0; i < keys_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, keys_.get(i));
    }
    for (int i = 0; i < revisedKeys_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, revisedKeys_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.TemporaryExposureKeyExport)) {
      return super.equals(obj);
    }
    protobuf.TemporaryExposureKeyExport other = (protobuf.TemporaryExposureKeyExport) obj;

    boolean result = true;
    result = result && (hasStartTimestamp() == other.hasStartTimestamp());
    if (hasStartTimestamp()) {
      result = result && (getStartTimestamp()
          == other.getStartTimestamp());
    }
    result = result && (hasEndTimestamp() == other.hasEndTimestamp());
    if (hasEndTimestamp()) {
      result = result && (getEndTimestamp()
          == other.getEndTimestamp());
    }
    result = result && (hasRegion() == other.hasRegion());
    if (hasRegion()) {
      result = result && getRegion()
          .equals(other.getRegion());
    }
    result = result && (hasBatchNum() == other.hasBatchNum());
    if (hasBatchNum()) {
      result = result && (getBatchNum()
          == other.getBatchNum());
    }
    result = result && (hasBatchSize() == other.hasBatchSize());
    if (hasBatchSize()) {
      result = result && (getBatchSize()
          == other.getBatchSize());
    }
    result = result && getSignatureInfosList()
        .equals(other.getSignatureInfosList());
    result = result && getKeysList()
        .equals(other.getKeysList());
    result = result && getRevisedKeysList()
        .equals(other.getRevisedKeysList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartTimestamp()) {
      hash = (37 * hash) + START_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTimestamp());
    }
    if (hasEndTimestamp()) {
      hash = (37 * hash) + END_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTimestamp());
    }
    if (hasRegion()) {
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion().hashCode();
    }
    if (hasBatchNum()) {
      hash = (37 * hash) + BATCH_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getBatchNum();
    }
    if (hasBatchSize()) {
      hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
    }
    if (getSignatureInfosCount() > 0) {
      hash = (37 * hash) + SIGNATURE_INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureInfosList().hashCode();
    }
    if (getKeysCount() > 0) {
      hash = (37 * hash) + KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getKeysList().hashCode();
    }
    if (getRevisedKeysCount() > 0) {
      hash = (37 * hash) + REVISED_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getRevisedKeysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.TemporaryExposureKeyExport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.TemporaryExposureKeyExport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.TemporaryExposureKeyExport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.TemporaryExposureKeyExport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.TemporaryExposureKeyExport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protobuf.TemporaryExposureKeyExport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.TemporaryExposureKeyExport)
      protobuf.TemporaryExposureKeyExportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_TemporaryExposureKeyExport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_TemporaryExposureKeyExport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.TemporaryExposureKeyExport.class, protobuf.TemporaryExposureKeyExport.Builder.class);
    }

    // Construct using protobuf.TemporaryExposureKeyExport.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSignatureInfosFieldBuilder();
        getKeysFieldBuilder();
        getRevisedKeysFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      endTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      region_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      batchNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      batchSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (signatureInfosBuilder_ == null) {
        signatureInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        signatureInfosBuilder_.clear();
      }
      if (keysBuilder_ == null) {
        keys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        keysBuilder_.clear();
      }
      if (revisedKeysBuilder_ == null) {
        revisedKeys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        revisedKeysBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.TemporaryExposureKeyExportOuterClass.internal_static_protobuf_TemporaryExposureKeyExport_descriptor;
    }

    @java.lang.Override
    public protobuf.TemporaryExposureKeyExport getDefaultInstanceForType() {
      return protobuf.TemporaryExposureKeyExport.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.TemporaryExposureKeyExport build() {
      protobuf.TemporaryExposureKeyExport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.TemporaryExposureKeyExport buildPartial() {
      protobuf.TemporaryExposureKeyExport result = new protobuf.TemporaryExposureKeyExport(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.startTimestamp_ = startTimestamp_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.endTimestamp_ = endTimestamp_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.region_ = region_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.batchNum_ = batchNum_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.batchSize_ = batchSize_;
      if (signatureInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          signatureInfos_ = java.util.Collections.unmodifiableList(signatureInfos_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.signatureInfos_ = signatureInfos_;
      } else {
        result.signatureInfos_ = signatureInfosBuilder_.build();
      }
      if (keysBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          keys_ = java.util.Collections.unmodifiableList(keys_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.keys_ = keys_;
      } else {
        result.keys_ = keysBuilder_.build();
      }
      if (revisedKeysBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          revisedKeys_ = java.util.Collections.unmodifiableList(revisedKeys_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.revisedKeys_ = revisedKeys_;
      } else {
        result.revisedKeys_ = revisedKeysBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.TemporaryExposureKeyExport) {
        return mergeFrom((protobuf.TemporaryExposureKeyExport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.TemporaryExposureKeyExport other) {
      if (other == protobuf.TemporaryExposureKeyExport.getDefaultInstance()) return this;
      if (other.hasStartTimestamp()) {
        setStartTimestamp(other.getStartTimestamp());
      }
      if (other.hasEndTimestamp()) {
        setEndTimestamp(other.getEndTimestamp());
      }
      if (other.hasRegion()) {
        bitField0_ |= 0x00000004;
        region_ = other.region_;
        onChanged();
      }
      if (other.hasBatchNum()) {
        setBatchNum(other.getBatchNum());
      }
      if (other.hasBatchSize()) {
        setBatchSize(other.getBatchSize());
      }
      if (signatureInfosBuilder_ == null) {
        if (!other.signatureInfos_.isEmpty()) {
          if (signatureInfos_.isEmpty()) {
            signatureInfos_ = other.signatureInfos_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSignatureInfosIsMutable();
            signatureInfos_.addAll(other.signatureInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.signatureInfos_.isEmpty()) {
          if (signatureInfosBuilder_.isEmpty()) {
            signatureInfosBuilder_.dispose();
            signatureInfosBuilder_ = null;
            signatureInfos_ = other.signatureInfos_;
            bitField0_ = (bitField0_ & ~0x00000020);
            signatureInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSignatureInfosFieldBuilder() : null;
          } else {
            signatureInfosBuilder_.addAllMessages(other.signatureInfos_);
          }
        }
      }
      if (keysBuilder_ == null) {
        if (!other.keys_.isEmpty()) {
          if (keys_.isEmpty()) {
            keys_ = other.keys_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureKeysIsMutable();
            keys_.addAll(other.keys_);
          }
          onChanged();
        }
      } else {
        if (!other.keys_.isEmpty()) {
          if (keysBuilder_.isEmpty()) {
            keysBuilder_.dispose();
            keysBuilder_ = null;
            keys_ = other.keys_;
            bitField0_ = (bitField0_ & ~0x00000040);
            keysBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getKeysFieldBuilder() : null;
          } else {
            keysBuilder_.addAllMessages(other.keys_);
          }
        }
      }
      if (revisedKeysBuilder_ == null) {
        if (!other.revisedKeys_.isEmpty()) {
          if (revisedKeys_.isEmpty()) {
            revisedKeys_ = other.revisedKeys_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureRevisedKeysIsMutable();
            revisedKeys_.addAll(other.revisedKeys_);
          }
          onChanged();
        }
      } else {
        if (!other.revisedKeys_.isEmpty()) {
          if (revisedKeysBuilder_.isEmpty()) {
            revisedKeysBuilder_.dispose();
            revisedKeysBuilder_ = null;
            revisedKeys_ = other.revisedKeys_;
            bitField0_ = (bitField0_ & ~0x00000080);
            revisedKeysBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRevisedKeysFieldBuilder() : null;
          } else {
            revisedKeysBuilder_.addAllMessages(other.revisedKeys_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.TemporaryExposureKeyExport parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.TemporaryExposureKeyExport) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long startTimestamp_ ;
    /**
     * <pre>
     * Time window of keys in this batch based on arrival to server, in UTC seconds.
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     */
    public boolean hasStartTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Time window of keys in this batch based on arrival to server, in UTC seconds.
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     */
    public long getStartTimestamp() {
      return startTimestamp_;
    }
    /**
     * <pre>
     * Time window of keys in this batch based on arrival to server, in UTC seconds.
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     */
    public Builder setStartTimestamp(long value) {
      bitField0_ |= 0x00000001;
      startTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time window of keys in this batch based on arrival to server, in UTC seconds.
     * </pre>
     *
     * <code>optional fixed64 start_timestamp = 1;</code>
     */
    public Builder clearStartTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long endTimestamp_ ;
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     */
    public boolean hasEndTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     */
    public long getEndTimestamp() {
      return endTimestamp_;
    }
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     */
    public Builder setEndTimestamp(long value) {
      bitField0_ |= 0x00000002;
      endTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional fixed64 end_timestamp = 2;</code>
     */
    public Builder clearEndTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object region_ = "";
    /**
     * <pre>
     * Region for which these keys came from, such as country.
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Region for which these keys came from, such as country.
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          region_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Region for which these keys came from, such as country.
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Region for which these keys came from, such as country.
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public Builder setRegion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      region_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Region for which these keys came from, such as country.
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public Builder clearRegion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      region_ = getDefaultInstance().getRegion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Region for which these keys came from, such as country.
     * </pre>
     *
     * <code>optional string region = 3;</code>
     */
    public Builder setRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      region_ = value;
      onChanged();
      return this;
    }

    private int batchNum_ ;
    /**
     * <pre>
     * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     */
    public boolean hasBatchNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     */
    public int getBatchNum() {
      return batchNum_;
    }
    /**
     * <pre>
     * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     */
    public Builder setBatchNum(int value) {
      bitField0_ |= 0x00000008;
      batchNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For example, file 2 in batch size of 10. Ordinal, 1-based numbering.
     * Note: Not yet supported on iOS.
     * </pre>
     *
     * <code>optional int32 batch_num = 4;</code>
     */
    public Builder clearBatchNum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      batchNum_ = 0;
      onChanged();
      return this;
    }

    private int batchSize_ ;
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public int getBatchSize() {
      return batchSize_;
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public Builder setBatchSize(int value) {
      bitField0_ |= 0x00000010;
      batchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public Builder clearBatchSize() {
      bitField0_ = (bitField0_ & ~0x00000010);
      batchSize_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<protobuf.SignatureInfo> signatureInfos_ =
      java.util.Collections.emptyList();
    private void ensureSignatureInfosIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        signatureInfos_ = new java.util.ArrayList<protobuf.SignatureInfo>(signatureInfos_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.SignatureInfo, protobuf.SignatureInfo.Builder, protobuf.SignatureInfoOrBuilder> signatureInfosBuilder_;

    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public java.util.List<protobuf.SignatureInfo> getSignatureInfosList() {
      if (signatureInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(signatureInfos_);
      } else {
        return signatureInfosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public int getSignatureInfosCount() {
      if (signatureInfosBuilder_ == null) {
        return signatureInfos_.size();
      } else {
        return signatureInfosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public protobuf.SignatureInfo getSignatureInfos(int index) {
      if (signatureInfosBuilder_ == null) {
        return signatureInfos_.get(index);
      } else {
        return signatureInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder setSignatureInfos(
        int index, protobuf.SignatureInfo value) {
      if (signatureInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignatureInfosIsMutable();
        signatureInfos_.set(index, value);
        onChanged();
      } else {
        signatureInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder setSignatureInfos(
        int index, protobuf.SignatureInfo.Builder builderForValue) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        signatureInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(protobuf.SignatureInfo value) {
      if (signatureInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(value);
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(
        int index, protobuf.SignatureInfo value) {
      if (signatureInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(index, value);
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(
        protobuf.SignatureInfo.Builder builderForValue) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(builderForValue.build());
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addSignatureInfos(
        int index, protobuf.SignatureInfo.Builder builderForValue) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        signatureInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder addAllSignatureInfos(
        java.lang.Iterable<? extends protobuf.SignatureInfo> values) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signatureInfos_);
        onChanged();
      } else {
        signatureInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder clearSignatureInfos() {
      if (signatureInfosBuilder_ == null) {
        signatureInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        signatureInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public Builder removeSignatureInfos(int index) {
      if (signatureInfosBuilder_ == null) {
        ensureSignatureInfosIsMutable();
        signatureInfos_.remove(index);
        onChanged();
      } else {
        signatureInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public protobuf.SignatureInfo.Builder getSignatureInfosBuilder(
        int index) {
      return getSignatureInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public protobuf.SignatureInfoOrBuilder getSignatureInfosOrBuilder(
        int index) {
      if (signatureInfosBuilder_ == null) {
        return signatureInfos_.get(index);  } else {
        return signatureInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public java.util.List<? extends protobuf.SignatureInfoOrBuilder> 
         getSignatureInfosOrBuilderList() {
      if (signatureInfosBuilder_ != null) {
        return signatureInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(signatureInfos_);
      }
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public protobuf.SignatureInfo.Builder addSignatureInfosBuilder() {
      return getSignatureInfosFieldBuilder().addBuilder(
          protobuf.SignatureInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public protobuf.SignatureInfo.Builder addSignatureInfosBuilder(
        int index) {
      return getSignatureInfosFieldBuilder().addBuilder(
          index, protobuf.SignatureInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Information about associated signatures
     * </pre>
     *
     * <code>repeated .protobuf.SignatureInfo signature_infos = 6;</code>
     */
    public java.util.List<protobuf.SignatureInfo.Builder> 
         getSignatureInfosBuilderList() {
      return getSignatureInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.SignatureInfo, protobuf.SignatureInfo.Builder, protobuf.SignatureInfoOrBuilder> 
        getSignatureInfosFieldBuilder() {
      if (signatureInfosBuilder_ == null) {
        signatureInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.SignatureInfo, protobuf.SignatureInfo.Builder, protobuf.SignatureInfoOrBuilder>(
                signatureInfos_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        signatureInfos_ = null;
      }
      return signatureInfosBuilder_;
    }

    private java.util.List<protobuf.TemporaryExposureKey> keys_ =
      java.util.Collections.emptyList();
    private void ensureKeysIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        keys_ = new java.util.ArrayList<protobuf.TemporaryExposureKey>(keys_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.TemporaryExposureKey, protobuf.TemporaryExposureKey.Builder, protobuf.TemporaryExposureKeyOrBuilder> keysBuilder_;

    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public java.util.List<protobuf.TemporaryExposureKey> getKeysList() {
      if (keysBuilder_ == null) {
        return java.util.Collections.unmodifiableList(keys_);
      } else {
        return keysBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public int getKeysCount() {
      if (keysBuilder_ == null) {
        return keys_.size();
      } else {
        return keysBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public protobuf.TemporaryExposureKey getKeys(int index) {
      if (keysBuilder_ == null) {
        return keys_.get(index);
      } else {
        return keysBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder setKeys(
        int index, protobuf.TemporaryExposureKey value) {
      if (keysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeysIsMutable();
        keys_.set(index, value);
        onChanged();
      } else {
        keysBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder setKeys(
        int index, protobuf.TemporaryExposureKey.Builder builderForValue) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.set(index, builderForValue.build());
        onChanged();
      } else {
        keysBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(protobuf.TemporaryExposureKey value) {
      if (keysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeysIsMutable();
        keys_.add(value);
        onChanged();
      } else {
        keysBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(
        int index, protobuf.TemporaryExposureKey value) {
      if (keysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKeysIsMutable();
        keys_.add(index, value);
        onChanged();
      } else {
        keysBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(
        protobuf.TemporaryExposureKey.Builder builderForValue) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.add(builderForValue.build());
        onChanged();
      } else {
        keysBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addKeys(
        int index, protobuf.TemporaryExposureKey.Builder builderForValue) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.add(index, builderForValue.build());
        onChanged();
      } else {
        keysBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder addAllKeys(
        java.lang.Iterable<? extends protobuf.TemporaryExposureKey> values) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keys_);
        onChanged();
      } else {
        keysBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder clearKeys() {
      if (keysBuilder_ == null) {
        keys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        keysBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public Builder removeKeys(int index) {
      if (keysBuilder_ == null) {
        ensureKeysIsMutable();
        keys_.remove(index);
        onChanged();
      } else {
        keysBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public protobuf.TemporaryExposureKey.Builder getKeysBuilder(
        int index) {
      return getKeysFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public protobuf.TemporaryExposureKeyOrBuilder getKeysOrBuilder(
        int index) {
      if (keysBuilder_ == null) {
        return keys_.get(index);  } else {
        return keysBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public java.util.List<? extends protobuf.TemporaryExposureKeyOrBuilder> 
         getKeysOrBuilderList() {
      if (keysBuilder_ != null) {
        return keysBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(keys_);
      }
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public protobuf.TemporaryExposureKey.Builder addKeysBuilder() {
      return getKeysFieldBuilder().addBuilder(
          protobuf.TemporaryExposureKey.getDefaultInstance());
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public protobuf.TemporaryExposureKey.Builder addKeysBuilder(
        int index) {
      return getKeysFieldBuilder().addBuilder(
          index, protobuf.TemporaryExposureKey.getDefaultInstance());
    }
    /**
     * <pre>
     * The TemporaryExposureKeys for initial release of keys.
     * Keys should be included in this list for initial release,
     * whereas revised or revoked keys should go in revised_keys.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey keys = 7;</code>
     */
    public java.util.List<protobuf.TemporaryExposureKey.Builder> 
         getKeysBuilderList() {
      return getKeysFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.TemporaryExposureKey, protobuf.TemporaryExposureKey.Builder, protobuf.TemporaryExposureKeyOrBuilder> 
        getKeysFieldBuilder() {
      if (keysBuilder_ == null) {
        keysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.TemporaryExposureKey, protobuf.TemporaryExposureKey.Builder, protobuf.TemporaryExposureKeyOrBuilder>(
                keys_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        keys_ = null;
      }
      return keysBuilder_;
    }

    private java.util.List<protobuf.TemporaryExposureKey> revisedKeys_ =
      java.util.Collections.emptyList();
    private void ensureRevisedKeysIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        revisedKeys_ = new java.util.ArrayList<protobuf.TemporaryExposureKey>(revisedKeys_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.TemporaryExposureKey, protobuf.TemporaryExposureKey.Builder, protobuf.TemporaryExposureKeyOrBuilder> revisedKeysBuilder_;

    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public java.util.List<protobuf.TemporaryExposureKey> getRevisedKeysList() {
      if (revisedKeysBuilder_ == null) {
        return java.util.Collections.unmodifiableList(revisedKeys_);
      } else {
        return revisedKeysBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public int getRevisedKeysCount() {
      if (revisedKeysBuilder_ == null) {
        return revisedKeys_.size();
      } else {
        return revisedKeysBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public protobuf.TemporaryExposureKey getRevisedKeys(int index) {
      if (revisedKeysBuilder_ == null) {
        return revisedKeys_.get(index);
      } else {
        return revisedKeysBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder setRevisedKeys(
        int index, protobuf.TemporaryExposureKey value) {
      if (revisedKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRevisedKeysIsMutable();
        revisedKeys_.set(index, value);
        onChanged();
      } else {
        revisedKeysBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder setRevisedKeys(
        int index, protobuf.TemporaryExposureKey.Builder builderForValue) {
      if (revisedKeysBuilder_ == null) {
        ensureRevisedKeysIsMutable();
        revisedKeys_.set(index, builderForValue.build());
        onChanged();
      } else {
        revisedKeysBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder addRevisedKeys(protobuf.TemporaryExposureKey value) {
      if (revisedKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRevisedKeysIsMutable();
        revisedKeys_.add(value);
        onChanged();
      } else {
        revisedKeysBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder addRevisedKeys(
        int index, protobuf.TemporaryExposureKey value) {
      if (revisedKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRevisedKeysIsMutable();
        revisedKeys_.add(index, value);
        onChanged();
      } else {
        revisedKeysBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder addRevisedKeys(
        protobuf.TemporaryExposureKey.Builder builderForValue) {
      if (revisedKeysBuilder_ == null) {
        ensureRevisedKeysIsMutable();
        revisedKeys_.add(builderForValue.build());
        onChanged();
      } else {
        revisedKeysBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder addRevisedKeys(
        int index, protobuf.TemporaryExposureKey.Builder builderForValue) {
      if (revisedKeysBuilder_ == null) {
        ensureRevisedKeysIsMutable();
        revisedKeys_.add(index, builderForValue.build());
        onChanged();
      } else {
        revisedKeysBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder addAllRevisedKeys(
        java.lang.Iterable<? extends protobuf.TemporaryExposureKey> values) {
      if (revisedKeysBuilder_ == null) {
        ensureRevisedKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, revisedKeys_);
        onChanged();
      } else {
        revisedKeysBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder clearRevisedKeys() {
      if (revisedKeysBuilder_ == null) {
        revisedKeys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        revisedKeysBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public Builder removeRevisedKeys(int index) {
      if (revisedKeysBuilder_ == null) {
        ensureRevisedKeysIsMutable();
        revisedKeys_.remove(index);
        onChanged();
      } else {
        revisedKeysBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public protobuf.TemporaryExposureKey.Builder getRevisedKeysBuilder(
        int index) {
      return getRevisedKeysFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public protobuf.TemporaryExposureKeyOrBuilder getRevisedKeysOrBuilder(
        int index) {
      if (revisedKeysBuilder_ == null) {
        return revisedKeys_.get(index);  } else {
        return revisedKeysBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public java.util.List<? extends protobuf.TemporaryExposureKeyOrBuilder> 
         getRevisedKeysOrBuilderList() {
      if (revisedKeysBuilder_ != null) {
        return revisedKeysBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(revisedKeys_);
      }
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public protobuf.TemporaryExposureKey.Builder addRevisedKeysBuilder() {
      return getRevisedKeysFieldBuilder().addBuilder(
          protobuf.TemporaryExposureKey.getDefaultInstance());
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public protobuf.TemporaryExposureKey.Builder addRevisedKeysBuilder(
        int index) {
      return getRevisedKeysFieldBuilder().addBuilder(
          index, protobuf.TemporaryExposureKey.getDefaultInstance());
    }
    /**
     * <pre>
     * TemporaryExposureKeys that have changed status.
     * Keys should be included in this list if they have changed status
     * or have been revoked.
     * </pre>
     *
     * <code>repeated .protobuf.TemporaryExposureKey revised_keys = 8;</code>
     */
    public java.util.List<protobuf.TemporaryExposureKey.Builder> 
         getRevisedKeysBuilderList() {
      return getRevisedKeysFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protobuf.TemporaryExposureKey, protobuf.TemporaryExposureKey.Builder, protobuf.TemporaryExposureKeyOrBuilder> 
        getRevisedKeysFieldBuilder() {
      if (revisedKeysBuilder_ == null) {
        revisedKeysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protobuf.TemporaryExposureKey, protobuf.TemporaryExposureKey.Builder, protobuf.TemporaryExposureKeyOrBuilder>(
                revisedKeys_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        revisedKeys_ = null;
      }
      return revisedKeysBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.TemporaryExposureKeyExport)
  }

  // @@protoc_insertion_point(class_scope:protobuf.TemporaryExposureKeyExport)
  private static final protobuf.TemporaryExposureKeyExport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.TemporaryExposureKeyExport();
  }

  public static protobuf.TemporaryExposureKeyExport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<TemporaryExposureKeyExport>
      PARSER = new com.google.protobuf.AbstractParser<TemporaryExposureKeyExport>() {
    @java.lang.Override
    public TemporaryExposureKeyExport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemporaryExposureKeyExport(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemporaryExposureKeyExport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemporaryExposureKeyExport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.TemporaryExposureKeyExport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

